### ISSUE TITLE
links to "anatomy/" still in a lot of places

### ISSUE THREAD

**Issue by mpizenberg** [exercism/docs#101]
Hi, it seems the `anatomy/` has been renamed into `building/`. I noticed it by arriving on a 404 from a link in another issue. It seems there are still many places referencing the old name and using old links like in the readme of this repo for example.

**Comment by iHiD** [comment]
Thanks for the heads up. 🙂 

I imagine most of the links in here are currently broken. We'll go through and fix everything (and add a link-checker) before launch.
