### ISSUE TITLE
Consider moving "Migrate from Travis" to it's own doc

### ISSUE THREAD

**Issue by iHiD** [exercism/docs#104]
Consider moving "Migrate from Travis" to it's own doc.

Rationale:
1. It's irrelevant for 99% of people wanting to learn about our CI, but makes the doc feel longer/scarier by being there.
2. At the top we link to it straight away for people who want to learn about it - having a specific doc for it feels like a nice optimisation to send them to.

**Comment by SaschaMann** [comment]
Do you know if there are any tracks left on Travis? Otherwise we might as well delete it.

**Comment by iHiD** [comment]
There are [somewhere just below 54](https://github.com/search?q=org%3Aexercism+filename%3Atravis.yml&type=Code&ref=advsearch&l=&l=)... **sigh**

**Comment by iHiD** [comment]
(These will go on my "Good first issues for getting some reputation" page 😉)
