### ISSUE TITLE
Enhancement Idea: move the language getting started guides to the language tracks.

### ISSUE THREAD

**Issue by verdammelt** [exercism/docs#108]
While getting the xLisp track started I noticed that I needed to make a change in the xlisp repo and then make a change in this repo for changes to the starting state. I was thinking it might be good to have the getting started guides packaged with the language tracks that way things that need to change together are packaged together.

Just a thought.

**Comment by kytrinyx** [comment]
I'm deprecating this repo in favor of moving the specific bits of documentation closer to where it's needed. See the README for details.

**Comment by kytrinyx** [comment]
Oh, also: this is solved :) Yay. For once.
