### ISSUE TITLE
lint: what is a "titleized string"?

### ISSUE THREAD

**Issue by ee7** [exercism/docs#114]
[lint.md](https://github.com/exercism/docs/blob/main/building/configlet/lint.md) contains:
> - The `"concepts[].name"` key is required
> - The `"concepts[].name"` value must be a non-empty, non-blank, titleized string

What is the definition of "titleized string"? Some possibilities:
1. A string that has an uppercase letter as the first character
1. A string that, if the first character is a letter, that letter must be uppercase (this allows e.g. a digit as the first character)
1. A string where each word has an uppercase character as the first letter
1. A string where each word has an uppercase character as the first letter, and the other letters are lowercase
1. Something else

Can we specify a regular expression that it should match?

And as an aside, is it deliberate that the below aren't "titleized strings"?
> - The `"exercises.concept[].name"` value must be a non-empty, non-blank string
> - The `"exercises.practice[].name"` value must be a non-empty, non-blank string

If they are supposed to be titleized, is e.g. `Sum of Multiples` a titleized string, or should it be `Sum Of Multiples`?

**Comment by iHiD** [comment]
Titles can contain unicode and can start with numbers, and potentially start with lower case letters (e.g. An exercise called "nth degree" should probably not be "Nth degree" etc).

The meaning of titliezed is something that is written in natural english (as opposed to kebab-case) that follows some set of [Title case](https://en.wikipedia.org/wiki/Title_case) rules - probably Chicago for my money. As they can contain other unicode characters (including emoji) and numbers, I doubt we'll be able to find a sane regexp.

> And as an aside, is it deliberate that the below aren't "titleized strings"?

No, they should be.

> If they are supposed to be titleized, is e.g. Sum of Multiples a titleized string, or should it be Sum Of Multiples?

Sum of Multiples

**Comment by ee7** [comment]
> follows some set of [Title case](https://en.wikipedia.org/wiki/Title_case) rules - probably Chicago for my money

OK, thanks. We can clarify that in the `lint.md` glossary when we get around to it.

> Sum of Multiples

OK. Currently it's "Sum Of Multiples" in every track `config.json` file, just FYI.

Counting the number of track `config.json` files that contain each string:
```
$ rg 'Sum Of Multiples' -l -g 'config.json' | wc -l
41
$ rg 'Sum of Multiples' -l -g 'config.json' | wc -l 
0
```

> No, they should be.

Follow-up questions, then:
1. Should acronyms be all-uppercase in the `name` of an exercise?
2. Should `configlet lint` enforce the correct capitalization of the `name` of a prob-specs exercise? 

Currently, nearly every track uses the capitalizations of e.g.:
- Dnd Character
- Dot Dsl
- Etl
- Isbn Verifier
- Ocr Numbers
- Pov
- Rest Api
- Rna transcription
- Sgf Parsing

Counting the occurrences in track `config.json` files:
```
$ rg '"name": "Etl"' -g 'config.json' | wc -l 
39
$ rg '"name": "ETL"' -g 'config.json' | wc -l 
1
```

The exercise name currently displays on exercism.lol as `Etl`, but it displayed on the v2 website as `ETL` - I guess there was special handling of them?

(The v2 website did display `Sum Of Multiples`, though).

**Comment by iHiD** [comment]
> OK. Currently it's "Sum Of Multiples" in every track config.json file, just FYI.

OK, Thanks.

> Should acronyms be all-uppercase in the name of an exercise?

Yeah, ETL not Etl

> Should configlet lint enforce the correct capitalization of the name of a prob-specs exercise?

That seems sensible to me where possible. I'd suggest having the `name` in problem-specs itself if it's not already. But I'd also say it's probably not the highest priority as updating names is easy and has low consequences. (Unlike say slugs, where changing is a bigger deal).
