### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by bartj3** [exercism/docs#133]
There seems to be some kind of encoding problem on a couple of getting started pages:

- [coffeescript](http://help.exercism.io/getting-started-with-coffeescript.html)
- [elixir](http://help.exercism.io/getting-started-with-elixir.html)
- [lua](http://help.exercism.io/getting-started-with-lua.html)

The issue seems to be with non ascii characters (which can be found in the code using `ack [^[:ascii:]]`).

This doesn't happen when I run lineman locally (on OSX) so it might be an encoding problem on the computer which is used to build and deploy? Which I guess is @kytrinyx's computer.

**Comment by kytrinyx** [comment]
Yeah, it's my computer. Oddly enough, it's OSX as well. I'll take a look. Thanks!

**Comment by kytrinyx** [comment]
It works fine on mine as well, but it's being built on a linux box. Thanks for reporting it!
