### ISSUE TITLE
Regression: Scheme Vanishes!

### ISSUE THREAD

**Issue by canweriotnow** [exercism/docs#137]
I swear it was listed in the sidebar, and http://help.exercism.io/getting-started-with-scheme.html didn't 404, less than 48 hours ago, but now that Scheme shows up in the main app, it seems to have disappeared from the docs...

:sob:

**Comment by kytrinyx** [comment]
wat! This is silly and I have no idea what happened! Looking now.

**Comment by canweriotnow** [comment]
Isn't "expect silliness" the first rule of software?

**Comment by kytrinyx** [comment]
It sure seems that way, but it always comes as a surprise. I appear to have never deployed it, or perhaps magically undeployed it at some point in the past couple of days.

**Comment by canweriotnow** [comment]
Ah, cool. Thanks for looking into it!
