### ISSUE TITLE
Provide context-free step-by-step Getting Started instructions for new-to-Java users

### ISSUE THREAD

**Issue by jtigger** [exercism/docs#146]
Java's a bit of a pain to get started with.  Let's reduce the number of support requests we get by providing step-by-step instructions.

Use @canweriotnow 's excellent walk-through: https://gist.github.com/canweriotnow/d60f9a784f8cc4f59301

**Comment by jtigger** [comment]
It's taking a while to get these fully baked and properly tested; this issue is to signal that I'm workin' on it! :)

**Comment by kytrinyx** [comment]
Sweet :) I just saw the first PR. I'll leave this open for a bit as we see what further requests come in after #147 is merged and deployed.

**Comment by jtigger** [comment]
Looks like we're not serving up HTML in UTF-8...

On my machine I see:
> "Step 1 — Install Java Development Kit 1.8"

on the deployed site I see:

> "Step 1 â€” Install Java Development Kit 1.8"

I notice that when served from the express app, locally, the `Content-Type` header includes the `charset=UTF-8` value; that is absent from the prod site.

Response headers from http://help.exercism.io/getting-started-with-java.html...

```
HTTP/1.1 200 OK
Connection: keep-alive
Date: Sun, 14 Jun 2015 05:50:11 GMT
Server: Apache/2.2.19 (Unix)
Last-Modified: Fri, 12 Jun 2015 14:06:41 GMT
Etag: "6a0542-3bf7-518529e03fe40"
Accept-Ranges: bytes
Content-Length: 15351
Content-Type: text/html
Via: 1.1 vegur
```

Response headers from http://localhost:8000/getting-started-with-java.html...

```
HTTP/1.1 200 OK
X-Powered-By: Express
Vary: Accept-Encoding
Accept-Ranges: bytes
ETag: "15351-1434260334000"
Date: Sun, 14 Jun 2015 05:51:34 GMT
Cache-Control: public, max-age=0
Last-Modified: Sun, 14 Jun 2015 05:38:54 GMT
Content-Type: text/html; charset=UTF-8
Content-Encoding: gzip
Connection: keep-alive
Transfer-Encoding: chunked
```

What's the word on configuring the prod instance to serve up UTF-8?

**Comment by kytrinyx** [comment]
I made the mistake of using a custom framework that I don't understand for the docs. I've been meaning to rewrite it as a ruby/sinatra thing (since I can do that in my sleep, except for the part where I'm actually sleeping and therefore not writing code).

That said... how hard can it be, right? :)

**Comment by kytrinyx** [comment]
I think I got it. Would you check on your end?

**Comment by canweriotnow** [comment]
Somebody called a PR I sent out of frustration excellent.

My FOSS heart is so warm and fuzzy :)

**Comment by jtigger** [comment]
@kytrinyx — solid.  Thanks!

**Comment by jtigger** [comment]
With that merge we have walkthroughs for the two key scenarios to support new-to-Java users.  I'm considering the OS X instructions sufficiently close as to be reasonably adaptable by anyone running a *nix distro.
