### ISSUE TITLE
Clarify use of `x:type` label

### ISSUE THREAD

**Issue by ee7** [exercism/docs#149]
The description of each `x:type` label might not convey the intention. The docs say that it "describes how much Exercism knowledge is required", but the description of each tag begins with "work on", which is the same as the description for `x:module`.

Should the description for each `x:type` label instead be something like "requires knowledge of foo"? 

I'm making this issue partly to ask: how do we intend an `x:type` label to be applied to a configlet issue/PR?

Currently [the docs](https://github.com/exercism/docs/blob/eb4abf37c5a7a51f9865928d7719721016cbe293/product/tasks.md) contain:

> ### Type tag
> 
> The `x:type/<value>` labels describe how much Exercism knowledge is required by the contributor.
> 
> | Tag              | Description                                                    |
> | ---------------- | -------------------------------------------------------------- |
> | `x:type/ci`      | Work on Continuous Integration (e.g. GitHub Actions workflows) |
> | `x:type/coding`  | Work on code that will run in production                       |
> | `x:type/content` | Work on content (e.g. exercises, concepts)                     |
> | `x:type/docker`  | Work on Dockerfiles                                            |
> | `x:type/docs`    | Work on Documentation                                          | 

Considering `x:type/content`:
A configlet issue might "require knowledge of Exercism content", so the label could match the initial description, but not the per-tag description (it isn't "work on content").

Considering `x:type/ci`:
Parts of `configlet` are run in CI, so some configlet issue might be "working on Continuous Integration", but it might not actually "require knowledge of Continuous Integration". 

---

It also seems like there is no `x:module` tag that can be applied to any configlet issue/PR, just FYI. So it's unclear to me how any configlet issue can show up in tasks, unless filtering just by action/size/knowledge.

> ### Module tag
> 
> The `x:module/<value>` labels indicate what part of Exercism the contributor will be working on.
> 
> | Tag                          | Description                 |
> | ---------------------------- | --------------------------- |
> | `x:module/analyzer`          | Work on Analyzers           |
> | `x:module/concept`           | Work on Concepts            |
> | `x:module/concept-exercise`  | Work on Concept Exercises   |
> | `x:module/generator`         | Work on Exercise generators |
> | `x:module/practice-exercise` | Work on Practice Exercises  |
> | `x:module/representer`       | Work on Representers        |
> | `x:module/test-runner`       | Work on Test Runners        |

**Comment by iHiD** [comment]
> The description of each x:type label might not convey the intention. The docs say that it "describes how much Exercism knowledge is required"

That sounds like the `knowledge` tag, not the `type` tag.

**Comment by iHiD** [comment]
> It also seems like there is no x:module tag that can be applied to any configlet issue/PR,

We'll probably have a module/configlet tag that gets added automatically to all issues in this repo.

**Comment by ee7** [comment]
> That sounds like the `knowledge` tag, not the `type` tag.

Ah, it looks like the fix for this issue involves changing the below. Currently, the description of `x:knowledge` and `x:type` is the same:

https://github.com/exercism/docs/blob/eb4abf37c5a7a51f9865928d7719721016cbe293/product/tasks.md#L33-L35

https://github.com/exercism/docs/blob/eb4abf37c5a7a51f9865928d7719721016cbe293/product/tasks.md#L70-L72
