### ISSUE TITLE
Teams

### ISSUE THREAD

**Issue by NobbZ** [exercism/docs#153]
According to my account page there seems to be a feature teams, I can't find any documentation about. Is this documentation on the to-do list?

**Comment by NobbZ** [comment]
Oh, and what are teams about?

**Comment by kytrinyx** [comment]
Hey! The teams feature is a completely not-thought-through hack that lets people keep track of each other. Ideally I want to replace it with a proper [activity stream](https://github.com/exercism/exercism.io/issues/1899).

It isn't documented (but it absolutely should be).

In the account page it should be possible to click on something like "add a team" or "create a team", which will let you invite people. This will give you a couple of things:

1. a team dashboard that shows you what everyone on the team has submitted, and
2. notifications when other people on the team submit an exercise

**Comment by kytrinyx** [comment]
I'm deprecating this repo in favor of moving the specific bits of documentation closer to where it's needed. See the README for details.
