### ISSUE TITLE
Add a list of mentors/responsible persons to a tracks language guide

### ISSUE THREAD

**Issue by NobbZ** [exercism/docs#155]
Add a section about whom to ping after one was a long time without any nits.

I've done quite a large number of exercises in C++ and started some random tracks. Many of them only have a very low count of views, and even less nits or “great code” clicks.

So I'd like to ping some users that are known valuable persons for that track or responsible for it, but I can't find a reliable source of valuable persons, and I don't want to ping only the tracks author.

**Comment by kytrinyx** [comment]
Yes, this would be very helpful.

This is actually one of the important problems that we're trying to figure out how to address from a number of different angles.

**Comment by kytrinyx** [comment]
I'm deprecating this repo in favor of moving the specific bits of documentation closer to where it's needed. See the README for details.
