### ISSUE TITLE
Proofread mentoring docs

### ISSUE THREAD

**Issue by iHiD** [exercism/docs#172]
The docs in the mentoring section (initially added here) need proofreading and probably fixing up. 

Please submit a PR with any changes that you think should be made!

**Comment by ghood97** [comment]
#257

**Comment by AthulMuralidhar** [comment]
hey @iHiD  can you please add what needs fixing here still? i went to the mentoring page here: https://exercism.org/mentoring  but i am a bit confused as to what sections in the page need proof reading. btw great product, great idea and im super stoked to help :)

**Comment by iHiD** [comment]
I won't have time to check soon (still firefighting from v3 launch), but @ErikSchierboom will know if this has been done or if there is still more to do here. He'll be able to let you know (or close this if there's nothing left) :)

Thanks for the support :)

**Comment by ErikSchierboom** [comment]
@AthulMuralidhar There has been some proofreading been done already, but a another pass will probably not hurt. You could check the following three pages:

- https://exercism.org/docs/mentoring/choosing-a-solution
- https://exercism.org/docs/mentoring/how-to-give-great-feedback
- https://exercism.org/docs/mentoring/markdown

**Comment by ghost** [comment]
Hey! I read through the three docs and only one thing really stood out:

In [https://exercism.org/docs/mentoring/choosing-a-solution](https://exercism.org/docs/mentoring/choosing-a-solution) there seems to be a missing image:
[TODO: Image of mentor discussion with areas marked].

**Comment by justin-m-morgan** [comment]
Given that the present images in the docs are hosted, would the preference be to include them colocated with the doc for someone else to move to their final destination, or leave the image task to someone at a higher pay-grade? ;)

**Comment by justin-m-morgan** [comment]
Is the "Automated Feedback" panel now removed from the Guidance panel?
