### ISSUE TITLE
Add to Exercism Alternatives

### ISSUE THREAD

**Issue by ZacharyRSmith** [exercism/docs#173]
[ElevatorSaga](http://play.elevatorsaga.com/) provides 19 increasingly difficult challenges in JavaScript. I find it fun, though it is not extensive enough to call it an Exercism "alternative".

<img width="1280" alt="screen shot 2015-10-18 at 10 33 06 pm" src="https://cloud.githubusercontent.com/assets/7988520/10568582/396ae950-75e8-11e5-87a2-c93207d51365.png">

<img width="1280" alt="screen shot 2015-10-18 at 10 30 22 pm" src="https://cloud.githubusercontent.com/assets/7988520/10568553/e435b348-75e7-11e5-97b3-7b973db27766.png">

**Comment by kytrinyx** [comment]
Sweet! No, anything that is an alternate place to go find exercises and challenges makes the list :)

**Comment by ZacharyRSmith** [comment]
Also, I haven't done any, but [this](http://nifty.stanford.edu/) looks very promising.

**Comment by kytrinyx** [comment]
that's brilliant! Would you add it to the list if you have a moment?

**Comment by kytrinyx** [comment]
This reminds me, I have to either figure out what has gone horribly wrong with the docs deployments, or move the documentation to x-common and deliver it to the main site via the x-api.

**Comment by ZacharyRSmith** [comment]
if i find/make the time, i'll try to figure out how to add em to the list. ( :

i also wonder if it would be beneficial to eventually add some kind of voting on this list? help people find the good stuff

**Comment by kytrinyx** [comment]
It's in `app/pages/topics/alternatives.md`

To be honest I don't really care too much about how they're ranked, only that we list them so people can look at if they want to. I'm sure folks will google them to find reviews and things if they're curious about what other people think.

**Comment by kytrinyx** [comment]
I'm deprecating this repo in favor of moving the specific bits of documentation closer to where it's needed. See the README for details.
