### ISSUE TITLE
Broken link in mentoring docs - Choosing solution to mentor 

### ISSUE THREAD

**Issue by JaPrad** [exercism/docs#239]
The link at the end of [this](https://github.com/exercism/docs/blob/main/mentoring/choosing_a_solution.md) page is broken

**Comment by JaPatGitHub** [comment]
Created PR #240

**Comment by ErikSchierboom** [comment]
@JaPatGitHub Thanks for reporting! This will be fixed in https://github.com/exercism/docs/pull/248/files.
