### ISSUE TITLE
"Creating a Test runner" instructions link does not work on Test Runner page

### ISSUE THREAD

**Issue by Bajger** [exercism/docs#253]
**Bug description**
Link on Exercism web docs to a page doesn't work and ends up with Internal server error 500.

**To Reproduce**
1. On Exercism web docs page: https://exercism.org/docs/building/tooling/test-runners
2. Click on  creating a Test Runner (that refer to: https://exercism.org/docs/building/tooling/creating-from-scratch.md)
3. I ends up with error: "500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong."

**Expected behavior**
Link to web doc works as expected and Creating a test runner instructions page is shown.

**Version information:**
 - OS: Tested on MacOS, Windows 10
 - Version of browser: Firefox 91.0.2 (64 bits)

**Expected development cost**
Probably just to fix a link?

**Additional context**
Please advice, what should be the correct link (if it is really wrong) and I can submit PR.

**Comment by ErikSchierboom** [comment]
The correct link is: https://exercism.org/docs/building/tooling/test-runners/creating-from-scratch A PR is much appreciated!
