### ISSUE TITLE
"General Tooling Docker information instructions" link on Docker web page navigates to same page.

### ISSUE THREAD

**Issue by Bajger** [exercism/docs#254]
**Bug description**
Clicking on "General Tooling Docker information instructions" link on Docker web page navigates to same page.

**To Reproduce**
1. Go to Docker page: https://exercism.org/docs/building/tooling/test-runners/docker
2. Click on "general Tooling docker information"
3. Same page is refreshed.

**Expected behavior**
A description about Docker tooling is shown.

**Screenshots**
![obrazek](https://user-images.githubusercontent.com/45875448/132635906-881bcec9-46d3-49bd-b72d-7d9d7852112f.png)

**Expected development cost**
Fix a link in MD file. Please advice, what should be correct one.

**Comment by ErikSchierboom** [comment]
The right link is: https://exercism.org/docs/building/tooling/docker

If you're interested in doing a PR, could you check if there are more places where the invalid link is used?

**Comment by Bajger** [comment]
Right! I found two links that are invalid (created separate issue for another). Probably this is overkill, but I'll leave it for these 2 links/issues and consequently PRs. I was particularly interested in how to make a test runner for Pharo track. Therefore I went trough this. I may go through rest of Building chapter and test links, if needed.

**Comment by ErikSchierboom** [comment]
That would be great!
