### ISSUE TITLE
Configlet sync docs out of date

### ISSUE THREAD

**Issue by junedev** [exercism/docs#264]
The `tests.toml` example given here https://exercism.org/docs/building/configlet/sync does not match the actual files in the tracks, e.g. https://github.com/exercism/javascript/blob/main/exercises/practice/grade-school/.meta/tests.toml.

@angelikatyborska said the docs are out of date.

**Comment by SaschaMann** [comment]
Some context: https://github.com/exercism/configlet/issues/207

**Comment by ee7** [comment]
Indeed, sorry - the `configlet sync` docs are only up to date at:
- https://github.com/exercism/configlet#configlet-sync
- https://github.com/exercism/problem-specifications#track-test-data

I'll update them here.

**Comment by junedev** [comment]
So I looked at the one place with the outdated info. 🙈

**Comment by junedev** [comment]
@ee7 Do you still intend to do the update here or should I try to make PR to fix the "docs" docs by copy & pasting the relevant parts of the updated README docs?

**Comment by ee7** [comment]
@junedev Thanks for the ping. I claim that I'm still going to do this - sorry it's taken so long.

`configlet sync` was completely overhauled in the meantime - now the configlet docs in prob-specs are outdated too. 

If I haven't done it by Monday then yes - please take over.

**Comment by junedev** [comment]
I created the PRs to update the docs and the problem spec readme according to the configlet readme.

**Comment by ErikSchierboom** [comment]
Both PRs have been merged so this can be closed. Thanks a ton @junedev!
