### ISSUE TITLE
Move TODO into Issues?

### ISSUE THREAD

**Issue by pertrai1** [exercism/docs#275]
I have seen places in the docs that have `TODO` that seems better to be listed here in issues rather than the public facing website.

![mentoring-discussion-todo](https://user-images.githubusercontent.com/442374/135734578-6f326b07-21ea-4d58-b970-f72fa35a4b58.jpg)

**Comment by iHiD** [comment]
Feel free to make an issue for each TODO - thanks. They were intended to be fixed before launch and I think most of them are straightforward to fix.

**Comment by ErikSchierboom** [comment]
With https://github.com/exercism/docs/pull/328 and https://github.com/exercism/docs/pull/327 merged, there are no longer any TODOs in this repo.

**Comment by iHiD** [comment]
Wahooo!

**Comment by loziniak** [comment]
On the other hand, TODOs can be seen as clear indicator of work-in-progress, and encourage contributors to work on docs perhaps? Giving instant gratification through TODO-figt :-)
