### ISSUE TITLE
Tags for Solidity

### ISSUE THREAD

**Issue by kotp** [exercism/docs#295]
There are three items added to this file that will still prevent
a "pass" from configlet lint.

These entries, or at least suitable entries, will need to be added to
the exercism/configlet/src/lint/track_config.nim file (as of this work).

See exercism/configlet#454 for the discussion concerning the above file
in regards to this language.  And the original PR at exercism/solidity#61.

**Comment by SaschaMann** [comment]
They seem to niche to me to be useful as tags. Searching for them would likely only result in Solidity which defeats the point of having those tags.

**Comment by kotp** [comment]
> They seem to niche to me to be useful as tags. Searching for them
> would likely only result in Solidity which defeats the point of having
> those tags.

That is true at the moment, but Solidity is not the only programming
langauge that works on that platform, nor is the only language that may
be considered "transactional", and at some point, each language that
introduced a tag fell into that very category for at least one tag.

**Comment by SaschaMann** [comment]
> at some point, each language that
introduced a tag fell into that very category for at least one tag.

IIRC no language introduced a tag, they were chosen based on common properties of languages instead.

**Comment by kotp** [comment]
Also, I believe Java probably is the language that introduced the JVM
tag.  Or the first language that started using the java virtual machine.
So the tag `runtime/evm` at least, if this is the first language that
runs there, will be introduced by a single language.

**Comment by ErikSchierboom** [comment]
> They seem to niche to me to be useful as tags. Searching for them would likely only result in Solidity which defeats the point of having those tags.

This was also my gut feeling.

> Also, I believe Java probably is the language that introduced the JVM
tag. Or the first language that started using the java virtual machine.
So the tag runtime/evm at least, if this is the first language that
runs there, will be introduced by a single language.

As Sascha mentioned, the tags were chosen to help differentiate between tracks. We purposefully didn't try to make an exhaustive list, but only one that could plausibly help students find the track they want. You could argue that the suggested tags also do that, but I'm unsure. We've also rejected new tags in the past if they didn't apply to multiple tracks.

I'll have a think on whether the suggested tags fit our goals. I'll keep you updated.

**Comment by kotp** [comment]
I do not know that all of them apply (and transactional, surely is controversial here)  But I do think `EVM` being one of them needs to be introduced, since it is the platform it runs on, and that is objectively true.

**Comment by ErikSchierboom** [comment]
We've had a chat internally, and we feel that the tags are valid _if_ they are shared with at least one other track.
