### ISSUE TITLE
The .meta/config.json spec is not aligned to the linting rules

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/docs#31]
https://github.com/exercism/docs/blob/4ef28e2ecb4a70f42c2974fa73f091c9a98b8127/anatomy/tracks/concept-exercises.md#file-metaconfigjson is not in line with https://github.com/exercism/docs/blob/7cd2be0d25f290407b9ddcdf8a3f42394da084b6/anatomy/tracks/configlet/linting.md#rule-exercisesconceptslugmetaconfigjson-is-valid

This means that what the spec is needs to be extracted from those two documents without a canonical resource. For example: `examplar` key was added (in the listing rule), but it's not documented anywhere else.

**Comment by iHiD** [comment]
To be clear (because I'm a little unsure of the title of this issue), are you pointing out that the `concept-exercises.md` hasn't yet been updated to include the `files` hash that we added on Thursday? (In which case I'll rename this issue to that for clarity). 

Or is there a bigger issues that you're getting at, which I'm not understanding? :)

**Comment by SleeplessByte** [comment]
I'm talking about there not being a clear spec in how `<slug>/.meta/config.json` should look :)

That's all 😄

**Comment by iHiD** [comment]
Yeah, so the example has not been updated to contain that key. As far as I can see, the rest of the example is correct. I'll put a PR together now :)

**Comment by SleeplessByte** [comment]
Cool! I hoped it was only that missing, but couldn't be certain.

**Comment by iHiD** [comment]
I've just checked. It's already been updated. You're not looking at `main` for some reason...

**Comment by iHiD** [comment]
https://github.com/exercism/docs/blob/main/anatomy/tracks/concept-exercises.md#file-metaconfigjson

<img width="1066" alt="Screenshot 2021-01-30 at 18 22 27" src="https://user-images.githubusercontent.com/286476/106364652-8f5cd700-6328-11eb-91de-6891b3dcaac8.png">

**Comment by iHiD** [comment]
Let me know if you followed a hard-coded link to those files from somewhere, where it should be a link to `main` instead. I've checked this repo and can't see it, but it could easily be in one of the other repos! :)

**Comment by SleeplessByte** [comment]
It was search.
