### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by elireiner** [exercism/docs#312]
In the [Creating an Analyzer page](https://github.com/exercism/docs/blob/main/building/tooling/analyzers/creating-from-scratch.md) the link in bullet two does not work. What is the article it needs to point to?

**Comment by ErikSchierboom** [comment]
The problem here is that the links are created for display on the website's docs part, not directly on GitHub. There, the link does work: https://exercism.org/docs/building/tooling/analyzers/creating-from-scratch We'll try at some point to fix this discrepancy.
