### ISSUE TITLE
Broken link to Chesterton's Fence in the "Being a Good Exercism Community Member" article

### ISSUE THREAD

**Issue by ghost** [exercism/docs#313]
Hi, 

Post "Being a Good Exercism Community Member" references a post on Chesterton's Fence:
https://github.com/exercism/docs/blob/e769a02351d02b62d12191684c5337d4d243b6a2/community/good-member/README.md?plain=1#L51

The link points to: `/docs/community/being-a-good-community-member/chestertons-fence` [broken link](https://github.com/exercism/docs/blob/main/docs/community/being-a-good-community-member/chestertons-fence)

Is this the correct reference? `docs/blob/main/community/good-member/chestertons-fence.md` [link](https://github.com/exercism/docs/blob/main/community/good-member/chestertons-fence.md) ?

**Comment by SaschaMann** [comment]
See the README:

> Please note that these docs are meant to be read at https://exercism.org/docs - not in this website. Links in this repository are relative to the website, not internally in this repo.

On the website, this link appears to work properly: https://exercism.org/docs/community/being-a-good-community-member

**Comment by ghost** [comment]
Thank you @SaschaMann. I'll close my issue
