### ISSUE TITLE
Fix broken relative links to repository files and directories

### ISSUE THREAD

**Issue by nahuakang** [exercism/docs#350]
## Motivation
I was reading `docs/building/configlet/README.md` when I found out that many relative links pointing to the `docs` repository files/dirs are redirected to `404`.

Relative links should be fixed so that new contributors have an easier time to navigate the docs and get started to work faster.

## Bad Relative URL Patterns
The problems can be summarized as following:

### 1. Incorrect relative links missing file extension
Example 1: `/docs/building/configlet/lint`
Fix: `/docs/building/configlet/lint.md`

Example 2: `/docs/building/configlet/generating-documents#document-concept-exercises-introductionmd-file`
Fix: `/docs/building/configlet/generating-documents.md#document-concept-exercises-introductionmd-file`

### 2. Incorrect subdirectory relative link to another subdirectory relative link
Given the repository structure:
```
docs/
    README.md
    building/
       README.md
       configlet/
           README.md
           generating-documents.md
       tracks/
           README.md
           concept-exercises.md
```

Example: Referencing `building/tracks/concept-exercises.md` inside `building/configlet/generating-documents.md`
Bad URL: `/docs/building/tracks/concept-exercises`
Fix:  `../tracks/concept-exercises.md`

### 3. Referencing parent-directory as as a sub-directory file
This does not seem to be supported by Github? Probably better to just use full URL.

Example: Referencing parent directory `/building/configlet` from `/building/configlet/generating-documents.md`
Bad URL: `/docs/building/configlet`
Fix: `https://github.com/exercism/docs/tree/main/building/configlet`

## Contributing to this issue
Reference to the fix can be seen here: https://stackoverflow.com/a/43042868/6297414

Feel free to Examine one of the directories in the checklist below. If you find any broken relative links, fix them and submit a PR referencing this issue.

## Checklist
Relative links to the following directories should be double-checked:

- [x] `/docs/building/configlet/`
- [ ] `/docs/building/github/`
- [ ] `/docs/building/markdown/`
- [ ] `/docs/building/product/`
- [ ] `/docs/building/tooling/`
- [ ] `/docs/building/tracks/`

## Related PRs
- https://github.com/exercism/docs/pull/351

**Comment by SaschaMann** [comment]
Hi, thanks for the detailed issue.

As far as I understand, the docs are meant to be read on exercism.org/docs, where the links do work.

It would be best for Erik or Jeremy to fix the site gen of the website, so it works everywhere, but changing the links here will break them on the website.

**Comment by nahuakang** [comment]
@SaschaMann That makes sense to me now. In this case I can also close the PR and this issue :)
