### ISSUE TITLE
README.md file under building/github has broken links

### ISSUE THREAD

**Issue by vorenusCoA** [exercism/docs#413]
In the README.md file, under the "Guides" section, there are 3 broken links:

- [How to make a great Pull Request](https://github.com/exercism/docs/blob/main/docs/community/being-a-good-community-member/pull-requests)
- [The Contributors' Guide to Pull Requests](https://github.com/exercism/docs/blob/main/docs/building/github/contributors-pull-request-guide)
- [The Maintainers' Guide to Pull Requests](https://github.com/exercism/docs/blob/main/docs/building/github/maintainers-pull-request-guide)

I suggest deleting the first one since it looks like a duplicate from the "How to make a great Pull Request" from the starting paragraph of the same section.

For the second and third ones I think these would be the proper links:
[The Contributors' Guide to Pull Requests](https://exercism.org/docs/building/github/contributors-pull-request-guide)
[The Maintainers' Guide to Pull Requests](https://exercism.org/docs/building/github/maintainers-pull-request-guide)

Please let me know if it is ok to open a PR for this. Thanks!

**Comment by iHiD** [comment]
Thanks. Have you noticed the bit in bold at the top of the README in this repo?

All three of these links work when I click on them: https://exercism.org/docs/building/github

**Comment by vorenusCoA** [comment]
Hi @iHiD, thanks for pointing that out (I hadn't seen it before).

You are correct, in the Exercism site the links work fine. A couple of questions:

- I was reading the README for the exercism/java repo which pointed me to this [file](https://github.com/exercism/java/blob/main/CONTRIBUTING.md). Inside that file there is a link to the README we are talking about. Should that link point to the Exercism site instead?
- What do you think about removing the second link to the [How to make a great Pull Request](https://exercism.org/docs/community/being-a-good-community-member/pull-requests)?

**Comment by iHiD** [comment]
Great - thanks.

> Should that link point to the Exercism site instead?

Yes. If you'd like to PR that, we'll gladly merge. Pls @ErikSchierboom in the PR.

> What do you think about removing the second link to the How to make a great Pull Request?

I'll leave Erik to decide that 🙂

**Comment by vorenusCoA** [comment]
In order to have everything in the right place I will open an issue for updating the CONTRIBUTING file of the java track in the corresponding repo (and then will tag Erik in the PR).

Also, will open a new issue in this repo for removing the "extra link" and see if it is accepted.

Thank you @iHiD for the guidance.
