### ISSUE TITLE
Figure out how to serve a proper 404 page

### ISSUE THREAD

**Issue by kytrinyx** [exercism/docs#5]
it could be inspired by the 404 page on exercism: http://exercism.io/no-such-page

**Comment by bluerogue251** [comment]
Is this site hosted on Rackspace like the main app is?  If so, it's possible this might apply:

http://docs.rackspace.com/files/api/v1/cf-devguide/content/Set_Error_Pages_for_Static_Website-dle4005.html

I could give it a try to make a 404 page for this.

**Comment by kytrinyx** [comment]
Actually both this and the main app are still hosted on heroku. I'm going to rewrite the docs app to be a simple go binary and host it on rackspace, which will make it blindingly simple to serve a 404 page.

The problem has been that I don't really understand the lineman wrapper thing that I've been using, and which has turned out to not quite be a good fit for what this app needs to do.

**Comment by kytrinyx** [comment]
I'm deprecating this repo in favor of moving the specific bits of documentation closer to where it's needed. See the README for details.
