### ISSUE TITLE
specify exercism wide code of conduct using a public .github repository

### ISSUE THREAD

**Issue by ghost** [exercism/docs#60]
As a maintainer I would like the fancy green icons for my repository.
Besides vanity, I hope it will improve our rankings in the Proprietary Algorithms.

It looks like you can specify a default code of conduct for all public repositories within your organization:
https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file#about-default-community-health-files

I would appreciate this for a code of conduct. 
Thanks!

**Comment by iHiD** [comment]
https://github.com/exercism/.github/

**Comment by iHiD** [comment]
> As a maintainer I would like the fancy green icons for my repository.

Where does said green tick appear?

**Comment by SaschaMann** [comment]
If you're refering to the checklist in Insights -> Community, it doesn't actually work reliably. According to that list the Julia track lacks a readme, contributing guide and CoC, despite having all of those.

**Comment by ghost** [comment]
thanks @iHiD!
I checked the icons at: https://github.com/exercism/rust/community.
I did see the CoC appear when I prepared to open a PR just now.
Like Sascha, I do not see it there LOL. But it does show up in the PR process which seems more important.

**Comment by SaschaMann** [comment]
> Like Sascha, I do not see it there LOL. 

When I refresh on that page for the Rust track, the state of README and CoC change... 🤔

> But it does show up in the PR process which seems more important.

Yup, it would be good to have for that reason too.

**Comment by iHiD** [comment]
It changes for me every time I refresh 🤷  I've opened a support ticket and pointed them to this issue :)

**Comment by iHiD** [comment]
They've just responded saying it should now be fixed.

**Comment by ghost** [comment]
I verified it is. Complete with browser reload bingo. 
Thank you for coordinating @iHiD!
