### ISSUE TITLE
Key Features in config.json -- icons?

### ISSUE THREAD

**Issue by glennj** [exercism/docs#79]
https://github.com/exercism/docs/blob/main/anatomy/tracks/config-json.md#key-features

So the item does not get lost: a list of icons is promised as a TODO.

Does this imply there will be a finite set of key features to choose from?

**Comment by BethanyG** [comment]
I am curious about this as well, considering the "key features" for Python aren't necessarily "standard" (_batteries included_ for example).

**Comment by iHiD** [comment]
We'll determine icons for the key features once all/enough tracks have merged their key features. They others will get stuck with a subset of icons to choose from.
