### ISSUE TITLE
Do concept blurbs support Markdown?

### ISSUE THREAD

**Issue by SaschaMann** [exercism/docs#83]
Exercise blurbs do not support markdown according to https://github.com/exercism/docs/blob/e835d0de9bcee1825628b87542a5bf86a7fce5c9/anatomy/tracks/concept-exercises.md#file-metaconfigjson

The docs on Concepts don't specify whether or not the blurb supports Markdown. Does it?

**Comment by iHiD** [comment]
No they don't. PR appreciated.

**Comment by SaschaMann** [comment]
I'm blind, it's in https://github.com/exercism/docs/blob/main/anatomy/tracks/config-json.md#concepts
